function Hd = BPFhw
%BPFHW Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 24.1 and Signal Processing Toolbox 24.1.
% Generated on: 17-Nov-2025 20:55:17

% Butterworth Bandpass filter designed using FDESIGN.BANDPASS.

% All frequency values are in MHz.
Fs = 1;  % Sampling Frequency

Fstop1 = 0.063;       % First Stopband Frequency
Fpass1 = 0.22;        % First Passband Frequency
Fpass2 = 0.28;        % Second Passband Frequency
Fstop2 = 0.437;       % Second Stopband Frequency
Astop1 = 40;          % First Stopband Attenuation (dB)
Apass  = 1;           % Passband Ripple (dB)
Astop2 = 40;          % Second Stopband Attenuation (dB)
match  = 'stopband';  % Band to match exactly

% Construct an FDESIGN object and call its BUTTER method.
h  = fdesign.bandpass(Fstop1, Fpass1, Fpass2, Fstop2, Astop1, Apass, ...
                      Astop2, Fs);
Hd = design(h, 'butter', 'MatchExactly', match);

% [EOF]
