function Hd = IIR_tx
%IIR_TX Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 24.1 and Signal Processing Toolbox 24.1.
% Generated on: 07-Nov-2025 14:15:58

% Butterworth Lowpass filter designed using FDESIGN.LOWPASS.

% All frequency values are in MHz.
Fs = 1;  % Sampling Frequency

Fpass = 0.02;        % Passband Frequency
Fstop = 0.48;        % Stopband Frequency
Apass = 1;           % Passband Ripple (dB)
Astop = 30;          % Stopband Attenuation (dB)
match = 'stopband';  % Band to match exactly

% Construct an FDESIGN object and call its BUTTER method.
h  = fdesign.lowpass(Fpass, Fstop, Apass, Astop, Fs);
Hd = design(h, 'butter', 'MatchExactly', match);

% [EOF]
