function Hd = LPFRxhw
%LPFRXHW Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 24.1 and Signal Processing Toolbox 24.1.
% Generated on: 17-Nov-2025 16:46:18

% Butterworth Lowpass filter designed using FDESIGN.LOWPASS.

% All frequency values are in MHz.
Fs = 1;  % Sampling Frequency

Fpass = 0.17;        % Passband Frequency
Fstop = 0.33;        % Stopband Frequency
Apass = 1;           % Passband Ripple (dB)
Astop = 32;          % Stopband Attenuation (dB)
match = 'stopband';  % Band to match exactly

% Construct an FDESIGN object and call its BUTTER method.
h  = fdesign.lowpass(Fpass, Fstop, Apass, Astop, Fs);
Hd = design(h, 'butter', 'MatchExactly', match);

% [EOF]
