function Hd = LPF
%LPF Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 24.1 and Signal Processing Toolbox 24.1.
% Generated on: 03-Oct-2025 17:27:53

% Equiripple Lowpass filter designed using the FIRPM function.

% All frequency values are in MHz.
Fs = 1;  % Sampling Frequency

Fpass = 0.1;             % Passband Frequency
Fstop = 0.2;             % Stopband Frequency
Dpass = 0.028774368332;  % Passband Ripple
Dstop = 0.01;            % Stopband Attenuation
dens  = 20;              % Density Factor

% Calculate the order from the parameters using FIRPMORD.
[N, Fo, Ao, W] = firpmord([Fpass, Fstop]/(Fs/2), [1 0], [Dpass, Dstop]);

% Calculate the coefficients using the FIRPM function.
b  = firpm(N, Fo, Ao, W, {dens});
Hd = dfilt.dffir(b);

% [EOF]
