function Hd = IIR
%IIR Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 24.1 and Signal Processing Toolbox 24.1.
% Generated on: 17-Oct-2025 17:25:01

% Butterworth Lowpass filter designed using FDESIGN.LOWPASS.

% All frequency values are in MHz.
Fs = 1;  % Sampling Frequency

Fpass = 0.015625;    % Passband Frequency
Fstop = 0.03125;     % Stopband Frequency
Apass = 1;           % Passband Ripple (dB)
Astop = 18;          % Stopband Attenuation (dB)
match = 'stopband';  % Band to match exactly

% Construct an FDESIGN object and call its BUTTER method.
h  = fdesign.lowpass(Fpass, Fstop, Apass, Astop, Fs);
Hd = design(h, 'butter', 'MatchExactly', match);

% [EOF]
